# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Run clean install
      run: |
        npm cache clean --force
        npm cache verify
        npm install
      
    - name: Run build
      run: npm run build --if-present
    
    - name: Run tests
      run: npm test
      env:  
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        USER_ID: ${{ secrets.USER_ID }}
        APP_URL: ${{ secrets.APP_URL }}
        SIGNER_EMAIL: ${{ secrets.SIGNER_EMAIL }}
        SIGNER_NAME: ${{ secrets.SIGNER_NAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
